services:
- type: web
  name: nextjs-static
  env: static
  plan: free
  repo: https://github.com/PaulBratslavsky/render-next-frontend

  buildCommand: yarn; yarn build; yarn next export
  staticPublishPath: out
  pullRequestPreviewsEnabled: true
  envVars:
  - key: NODE_ENV
    value: production
  - key: STRAPI_URL_BASE
    sync: false