- type: web
  name: render-deploy-next
  env: static
  buildCommand: yarn; yarn build; yarn next export
  staticPublishPath: out
  pullRequestPreviewsEnabled: true     # optional

  envVars:
  - key: NODE_ENV
    value: production
  - key: STRAPI_URL_BASE
    sync: false