services:
- type: web
  name: render-next-frontend
  env: node
  plan: free
  repo: https://github.com/PaulBratslavsky/render-next-frontend
  buildCommand: yarn; yarn build
  startCommand: yarn start
  envVars:
  - key: NODE_ENV
    value: production

- type: web
  name: nextjs-static
  env: static
  buildCommand: yarn; yarn build; yarn next export
  staticPublishPath: out
  pullRequestPreviewsEnabled: true
  envVars:
  - key: NODE_ENV
    value: production
  - key: STRAPI_URL_BASE
    sync: false